name: ask_pdf
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.4.5
  flutter_hooks: ^0.20.3
  flutter_spinkit: ^5.1.0
  riverpod_annotation: ^2.3.0
  flutter_dotenv: ^5.1.0
  animated_text_kit: ^4.2.2
  syncfusion_flutter_pdf: ^23.1.42
  path_provider: ^2.1.1
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_core: ^2.30.1
  firebase_storage: any
  get_storage: ^2.1.1
  fluttertoast: ^8.0.8
  file_picker: ^8.0.1
  uuid: ^4.4.0
  google_fonts: ^6.2.1
  pinecone: ^0.6.0
  bot_toast: ^4.0.1
  flutter_svg: ^2.0.10+1
  langchain_openai: ^0.0.13
  langchain:
    git:
      url: https://github.com/tayormi/langchain_dart
      ref: 49d39e4615dfcdadbd4c921d02a5e6315c577af4
      path: packages/langchain
  langchain_pinecone:
    git:
      url: https://github.com/tayormi/langchain_dart
      ref: 49d39e4615dfcdadbd4c921d02a5e6315c577af4
      path: packages/langchain_pinecone

dependency_overrides:
  langchain:
    git:
      url: https://github.com/tayormi/langchain_dart
      ref: 49d39e4615dfcdadbd4c921d02a5e6315c577af4
      path: packages/langchain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  custom_lint:
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3






flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/pdf/
    - assets/images/
    - assets/svgs/
    - assets/fonts/
    - .env
  fonts:
    - family: Luminosity
      fonts:
        - asset: assets/fonts/Luminosity.ttf
          weight: 100